### ISSUE TITLE
Infinite loop on bad input.

### ISSUE THREAD

**Issue by jneem** [saphyr-rs/saphyr#14]
While doing some fuzzing, I found that on the input "{---", saphyr-parser will enter an infinite loop and eat all the available memory. The loop is in `fetch_more_tokens`; the problem is that each time through the loop it wants more tokens, but then `fetch_next_token` retrieves an empty scalar and doesn't consume any input. Therefore, `self.tokens` just fills up with empty scalars.

**Comment by Ethiraric** [comment]
I had started a big comment explaining that I couldn't reproduce and I could not really see why. Turns out I probably accidentally fixed it in 95fe3fe when I noticed we fail to parse a `yaml-test-suite` test description file. The issue I encountered looks very similar.

I have added [your test](https://github.com/saphyr-rs/saphyr-parser/pull/14/files#diff-6b577c9a34766ccdaecd266ae93feb8510e3ce597fe96a35467f8ae06df0e930R170) and changed the error message (the mark points to EOF now rather than the first `-`). I preserved your authorship when [transferring it here](https://github.com/saphyr-rs/saphyr/commit/982407774e0ef97157aaf7e3b056bf3157a9ff7c).

On an unrelated note, do you have a setup you could share for fuzzing?

**Comment by Ethiraric** [comment]
The infinite loop happened when a plain scalar started with `...`. I pushed a fix to `master`.

The fuzzer still takes less than a couple seconds to find a crash, so I'll keep on playing with it and fixing things. Thanks a lot for adding it, I feel like it will keep me busy for a while.
