### ISSUE TITLE
Bools are parsed using `parse::<bool>()`, but YAML actually supports additional values

### ISSUE THREAD

**Issue by tliron** [saphyr-rs/saphyr#21]
The Saphyr code: [here](https://github.com/saphyr-rs/saphyr/blob/c81784cc014cab9fd734375f9ecbdd626462eed2/saphyr/src/loader.rs#L99) and [here](https://github.com/saphyr-rs/saphyr/blob/c81784cc014cab9fd734375f9ecbdd626462eed2/saphyr/src/yaml.rs#L229).

[The YAML spec](https://yaml.org/type/bool.html).

**Comment by bourumir-wyngs** [comment]
Yes,
```
 y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF
```

**Comment by Ethiraric** [comment]
I'll close this issue due to [a planned refactoring](https://github.com/saphyr-rs/saphyr/issues/18#issuecomment-2498606825) which would make interpreting scalars `saphyr`'s consumers' job.

I'd like to note that the link to `yaml.org` is not the specification but a draft, and applies to YAML 1.1 and not YAML 1.2. I especially do _not_ want to support `no` being parsed as a boolean to avoid [the Norway problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/).

**Comment by tliron** [comment]
Thanks for this. The problem is definitely not yours, it's the lax spec causing huge discrepancies between different parsers out there. Out in the wild there are non-standard documents...

**Comment by tliron** [comment]
By the way, if you don't want to support legacy 1.1 values, then you should also not support `~` for null, which you do right now.

I've decided in my own code to support a "legacy" mode where these quirky values are supported. Otherwise it will be strict 1.2.

**Comment by Ethiraric** [comment]
That is indeed a pain. Although `~` does not concern me much, empty strings do. There is no scalar type for a null value. I guess this would be an empty scalar?

```yaml
foo:
```

Would resolve to the following events:
```
MappingStart
Scalar("foo", style: plain)
Scalar("", style: plain)
MappingEnd
```

`Null` would be a variant that would be coerced into `Scalar`, since it only appears in [10.3.2](https://yaml.org/spec/1.2.2/#1032-tag-resolution) in the core schema. This however makes `foo:` and `foo: ''` identical as a `Yaml` object. The only difference in style would be in the parser events, which are discarded once the `Yaml` object is built.

The `Yaml` enum would have functions to parse them as the core schema (so you could do something like `yaml_document.as_bool(); // Option<bool>`). There wouldn't be much change in how things are handled... Except for empty strings. I'll have to think more thoroughly about that.

**Comment by tliron** [comment]
There's a reason why many people hate YAML. :)

My thinking is this: Make a 1.2 compliant parser. It's a much tighter spec than 1.1 and it should be what we all use.

However, it *could* be nice to allow for a "legacy" mode, which would support some 1.1 documents. You don't have to offer any guarantees for compliance or completeness in that mode. So, for example, you can ignore the annoying empty-nothing null specification from draft 1.1, which honestly I have never seen used even in the old day of 1.1.

Users who really need a 1.1 compliant parsers. Well. I would imagine they would have bigger problems than this.

**Comment by Ethiraric** [comment]
We already are a YAML 1.2 compliant parser. The descriptions everywhere (README included) state that `saphyr` parses YAML 1.2 compliant documents.

I do not want to bother supporting 1.1 documents. I heavily dislike the idea of "no guarantee for compliance or completeness", because a 100% broken parser fits that description. If I were to add YAML 1.1 support, I'd do my best to support the entire specification. It's just that there are bigger issues with `saphyr` as of now that need to be addressed before I could consider expanding its scope (and oh, god, please let me never have to work with YAML 1.1).

----
> the annoying empty-nothing null specification

What do you mean by that? YAML 1.2 has plenty of those, such as `[:]` being equivalent to `[ {null: null} ]`.

**Comment by tliron** [comment]
Sigh. Actually, my mistake. There are 3 schemas mentioned in the YAML 1.2 spec: failsafe, JSON, and core.

The [core schema does add various value variants](https://yaml.org/spec/1.2.2/#1032-tag-resolution), including `~`.

**Comment by reneleonhardt** [comment]
@Ethiraric Is basic YAML 1.1 compatibility planned?
For example to support Kubernetes manifests:
https://kubernetes.io/docs/concepts/configuration/overview/

**Comment by Ethiraric** [comment]
No it isn't. Due to [the Norway Problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/), using `yes` or `no` in YAML has been considered an error for a long time.

Furthermore, your link explicitly states:
> To avoid this issue, it is recommended to always use true or false for boolean values in YAML manifests, and to quote any strings that may be confused with booleans, such as "yes" or "no".

**Comment by reneleonhardt** [comment]
I didn't write the Kubernetes documentation or YAML compatibility in Kubernetes code, it's not "my" link 😄

Just wanted to know if Kubernetes manifests would be a possible use case for this library.
There are many libraries, apps and services relying on k8s.
https://github.com/topics/k8s

(Disclaimer: Not my link either 🙂)

**Comment by tliron** [comment]
@reneleonhardt FYI, Kubernetes manifests can be written in JSON, too. Actually they were in JSON originally (and are still processed as JSON internally). YAML manifests was a later addition.

**Comment by Ethiraric** [comment]
>  it's not "my" link 😄

Sorry, I meant it as _the one you gave me_.

An issue with YAML is that malpractice is rampant. There are countless tools with their own quirks regarding YAML. YAML 1.1's handling of boolean is widely regarded as a design mistake. In fact, we've had to change the `YamlEmitter` to emit quotes around `yes`, `no` and so on, because it broke someone's workflow when feeding `saphyr`'s output to a YAML 1.1 parser.

The feeling I have once I read the k8s documentation is that they meant something along the lines of:

> When we first released YAML support, we had a YAML 1.1 library. People were writing YAML 1.1 files. We would have liked changing to a YAML 1.2 library, but we'd risk breaking a ton of environments. Please write YAML 1.2 to avoid any issue.

_Most_ of Kubernetes files should be parsed correctly by `saphyr`. Those who don't should be updated to be YAML 1.2 compliant.

**Comment by reneleonhardt** [comment]
Thank you for your analysis!
Do you know of a good converter to migrate YAML 1.1 to 1.2?
For example, migrating exactly all those `"Yes"` variations to `true`.

**Comment by tliron** [comment]
@reneleonhardt The Python [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) parser supports both 1.1 and 1.2 (though not extremely well on either, from my experience). You can write a simple program to read 1.1 and write 1.2.

**Comment by Ethiraric** [comment]
Technically, you can do it with `saphyr`. If you [disable early parsing](https://docs.rs/saphyr/latest/saphyr/struct.YamlLoader.html#method.early_parse), you're left with [`Representation`](https://docs.rs/saphyr/latest/saphyr/enum.Yaml.html#variant.Representation) variants for scalars. You can then recursively walk your YAML object, look for all `Representation` variants and do something along the lines of:

```rs
fn replace_yaml11_bools(yaml: &mut Yaml) {
  if let Yaml::Representation(str, ScalarStyle::Plain, tag) = yaml {
    if ["y", "n", "yes", "no" /*, ... */].contains(str.as_ref()) && tag.map(|tag| !tag.is_yaml_core_schema()).unwrap_or(false) {
      yaml = Yaml::Value(Scalar::Boolean(/* parse here */));
    }
  }
}
```

Then, call [`parse_representation_recursive`](https://docs.rs/saphyr/latest/saphyr/enum.Yaml.html#method.parse_representation_recursive) on your root `Yaml` to let `saphyr` handle the rest of the parsing.

If you then pass your object through the emitter, you should get a YAML 1.2 compliant document.
